[package]
name = "e2e"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[package.metadata.dist]
dist = false

[dependencies]
wist-core = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
rusqlite = { workspace = true }
jiff = { workspace = true }
zerovec = { workspace = true }
base64 = { workspace = true }
tempfile = "3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
