[package]
name = "e2e"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[package.metadata.dist]
dist = false

[dev-dependencies]
tempfile = "3"
serde_json = { workspace = true }
reqwest = { workspace = true }
jiff = { workspace = true }
zerovec = { workspace = true }
